set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set hlsearch
set ignorecase
set smartcase
set relativenumber
set incsearch
set mouse=a
set scrolloff=5
set wildmenu
set backspace=indent,eol,start
